# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='decsription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='decsription',
            new_name='description',
        ),
    ]
