# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20181229_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='working_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='working_on',
            field=models.BooleanField(default=False),
        ),
    ]
