# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='token_amount',
            field=models.IntegerField(default=0),
        ),
    ]
